import re
from html.parser import HTMLParser

ALLOWED_TAGS = {"h2","h3","p","ul","li","table","tbody","tr","th","td","strong"}
BANNED_PHRASES = {
    "perfect for",
    "ideal for",
    "designed to elevate",
    "ultimate",
    "game-changing",
    "must-have",
    "whether you are",
}
PLACEHOLDER_PHRASES = {"n/a", "unknown", "not specified"}


class _HTMLAuditParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.errors = []

    def handle_starttag(self, tag, attrs):
        if tag not in ALLOWED_TAGS:
            self.errors.append(f"disallowed_tag:{tag}")
        if attrs:
            self.errors.append(f"attributes_not_allowed:{tag}")

    def handle_startendtag(self, tag, attrs):
        if tag not in ALLOWED_TAGS:
            self.errors.append(f"disallowed_tag:{tag}")
        if attrs:
            self.errors.append(f"attributes_not_allowed:{tag}")

    def handle_endtag(self, tag):
        if tag not in ALLOWED_TAGS:
            self.errors.append(f"disallowed_tag:{tag}")


def validate_product_html(html: str) -> list[str]:
    errors = []
    value = (html or "").strip()
    if not value:
        return ["empty_html"]

    parser = _HTMLAuditParser()
    try:
        parser.feed(value)
        parser.close()
    except Exception:
        errors.append("invalid_html")
    errors.extend(parser.errors)

    low = re.sub(r"\s+", " ", value).lower()
    for phrase in sorted(BANNED_PHRASES):
        if phrase in low:
            errors.append(f"banned_phrase:{phrase}")
    for phrase in sorted(PLACEHOLDER_PHRASES):
        if re.search(rf"\b{re.escape(phrase)}\b", low):
            errors.append(f"placeholder_phrase:{phrase}")

    if "<h2>" not in low:
        errors.append("missing_h2")
    if "<h3>technical specifications</h3>" not in low:
        errors.append("missing_technical_specifications")
    if "<table>" not in low:
        errors.append("missing_spec_table")

    return sorted(set(errors))


def may_replace_content(existing_html: str, content_origin: str = "") -> bool:
    # Manual content always wins. Blank content or content explicitly marked as
    # generated by this Fjord pipeline may be replaced on regeneration.
    if not (existing_html or "").strip():
        return True
    return (content_origin or "").strip().lower() == "fjord_auto"
